export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USERS = 'SET_USERS';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_MESSAGE_COUNT = 'SET_MESSAGE_COUNT';
export const UPDATE_ONE_MESSAGE_COUNT = 'UPDATE_ONE_MESSAGE_COUNT';
